export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const USERS_SUCCESS = 'USERS_SUCCESS'

export const LOGOUT = 'LOGOUT';